"""Fix case-insensitive name index to use column reference

Revision ID: 1c249d0dfbb5
Revises: add_emp_import_fields
Create Date: 2025-11-21 05:37:23.191211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c249d0dfbb5'
down_revision = 'add_emp_import_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    dialect = conn.dialect.name

    existing_indexes = {idx['name'] for idx in inspector.get_indexes('employees')}
    existing_tables = inspector.get_table_names()

    # Drop the broken index that uses literal 'name' string (if it exists)
    if 'ix_employee_name_lower' in existing_indexes:
        op.drop_index('ix_employee_name_lower', table_name='employees')

    # Recreate the index correctly using the name column (not literal string)
    # Re-check indexes after potential drop
    existing_indexes = {idx['name'] for idx in inspector.get_indexes('employees')}
    if 'ix_employee_name_lower' not in existing_indexes:
        op.create_index(
            'ix_employee_name_lower',
            'employees',
            [sa.text('lower(name)')],
            unique=False
        )

    # Clean up temporary table from previous migration (SQLite only - doesn't exist on PostgreSQL)
    if '_alembic_tmp_employees' in existing_tables:
        op.drop_table('_alembic_tmp_employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The _alembic_tmp_employees table is a SQLite artifact and should not be
    # recreated on downgrade. The index changes are essentially the same on
    # both upgrade and downgrade (recreating the index), so nothing to undo.
    pass
    # ### end Alembic commands ###
