"""Regenerate missing schema changes

Revision ID: 58becd6c9441
Revises: 0be04acd9951
Create Date: 2025-10-29 02:01:01.591100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58becd6c9441'
down_revision = '0be04acd9951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use inspection to check existing indexes/constraints (handles fresh PostgreSQL databases
    # where SQLAlchemy's create_all() may have already created these)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    # Helper to get existing indexes for a table
    def get_existing_indexes(table_name):
        try:
            return {idx['name'] for idx in inspector.get_indexes(table_name)}
        except Exception:
            return set()

    # Helper to get existing unique constraints for a table
    def get_existing_constraints(table_name):
        try:
            return {c['name'] for c in inspector.get_unique_constraints(table_name)}
        except Exception:
            return set()

    # employee_attendance table
    try:
        existing_constraints = get_existing_constraints('employee_attendance')
        with op.batch_alter_table('employee_attendance', schema=None) as batch_op:
            batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
            if 'uix_employee_date' not in existing_constraints:
                batch_op.create_unique_constraint('uix_employee_date', ['employee_id', 'attendance_date'])
    except Exception:
        pass

    # employees table indexes
    try:
        existing_indexes = get_existing_indexes('employees')
        with op.batch_alter_table('employees', schema=None) as batch_op:
            if 'idx_employees_active' not in existing_indexes:
                batch_op.create_index('idx_employees_active', ['is_active'], unique=False)
            if 'idx_employees_job_title' not in existing_indexes:
                batch_op.create_index('idx_employees_job_title', ['job_title'], unique=False)
            if 'idx_employees_supervisor' not in existing_indexes:
                batch_op.create_index('idx_employees_supervisor', ['is_supervisor'], unique=False)
            if 'idx_employees_termination' not in existing_indexes:
                batch_op.create_index('idx_employees_termination', ['termination_date'], unique=False)
    except Exception:
        pass

    # events table indexes
    try:
        existing_indexes = get_existing_indexes('events')
        with op.batch_alter_table('events', schema=None) as batch_op:
            if 'idx_events_date_range' not in existing_indexes:
                batch_op.create_index('idx_events_date_range', ['start_datetime', 'due_datetime'], unique=False)
            if 'idx_events_location' not in existing_indexes:
                batch_op.create_index('idx_events_location', ['location_mvid'], unique=False)
            if 'idx_events_scheduled' not in existing_indexes:
                batch_op.create_index('idx_events_scheduled', ['is_scheduled', 'condition'], unique=False)
            if 'idx_events_sync' not in existing_indexes:
                batch_op.create_index('idx_events_sync', ['sync_status'], unique=False)
            if 'idx_events_type' not in existing_indexes:
                batch_op.create_index('idx_events_type', ['event_type'], unique=False)
    except Exception:
        pass

    # paperwork_templates table
    try:
        existing_constraints = get_existing_constraints('paperwork_templates')
        with op.batch_alter_table('paperwork_templates', schema=None) as batch_op:
            batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
            batch_op.alter_column('created_at',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(),
                   existing_nullable=False,
                   existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
            batch_op.alter_column('updated_at',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(),
                   existing_nullable=False,
                   existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
            if 'uix_paperwork_templates_name' not in existing_constraints:
                batch_op.create_unique_constraint('uix_paperwork_templates_name', ['name'])
    except Exception:
        pass

    # schedules table indexes
    try:
        existing_indexes = get_existing_indexes('schedules')
        with op.batch_alter_table('schedules', schema=None) as batch_op:
            if 'idx_schedules_employee_date' not in existing_indexes:
                batch_op.create_index('idx_schedules_employee_date', ['employee_id', 'schedule_datetime'], unique=False)
            if 'idx_schedules_event' not in existing_indexes:
                batch_op.create_index('idx_schedules_event', ['event_ref_num'], unique=False)
            if 'idx_schedules_sync' not in existing_indexes:
                batch_op.create_index('idx_schedules_sync', ['sync_status', 'last_synced'], unique=False)
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('idx_schedules_sync')
        batch_op.drop_index('idx_schedules_event')
        batch_op.drop_index('idx_schedules_employee_date')

    with op.batch_alter_table('paperwork_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uix_paperwork_templates_name', type_='unique')
        # Skip creating indexes that weren't dropped in upgrade
        # batch_op.create_index(batch_op.f('idx_paperwork_templates_order'), ['display_order'], unique=False)
        # batch_op.create_index(batch_op.f('idx_paperwork_templates_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_type')
        batch_op.drop_index('idx_events_sync')
        batch_op.drop_index('idx_events_scheduled')
        batch_op.drop_index('idx_events_location')
        batch_op.drop_index('idx_events_date_range')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employees_termination')
        batch_op.drop_index('idx_employees_supervisor')
        batch_op.drop_index('idx_employees_job_title')
        batch_op.drop_index('idx_employees_active')

    with op.batch_alter_table('employee_attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uix_employee_date', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
